// Copyright Koninklijke Philips N.V. 2016
//
// All rights are reserved. Reproduction or transmission in whole or in part, in
// any form or by any means, electronic, mechanical or otherwise, is prohibited
// without the prior written consent of the copyright owner.

// ********************* WARNING *****************************
// * This file was automatically generated by Sense Composer *
// *      Modifying this file manually is frowned upon       *
// ***********************************************************
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>

namespace Pci { namespace Core
{

using namespace Sense;
using namespace Sense::ExperienceIdentity;

class AlluraIfrReviewPanel : public Panel
{
public:

	AlluraIfrReviewPanel(Control &parent)
	:
		Panel              (parent),
		fmTypeLabel        (*this),
		distalFmValueLabel (*this),
		separator          (*this),
		ifrTrendLabel      (*this),
		fmTrendValue       (*this)
	{
		layoutUpdateBegin();

		name                 = L"fmReviewPanel";
		size                 = Size(256, 220);
		border               = Margin(0, 0, 0, 0);
		edge                 = Margin(0, 0, 0, 0);
		colorEdge            = Color(0, 0, 0);
		color                = Color(0, 1, 1);

		fmTypeLabel.name                   = L"fmTypeLabel";
		fmTypeLabel.position               = Point(0, 26);
		fmTypeLabel.size                   = Size(256, 64);
		fmTypeLabel.font                   = Font(L"Philips Healthcare Font", 42, true, false, false, false, Font::Antialias::Low);
		fmTypeLabel.text                   = L"";
		fmTypeLabel.color                  = Palette::Black;
		fmTypeLabel.horizontalAlign        = HAlign::Center;

		distalFmValueLabel.name            = L"distalFmValueLabel";
		distalFmValueLabel.position        = Point(0, 92);
		distalFmValueLabel.size            = Size(256, 56);
		distalFmValueLabel.font            = Font(L"Philips Healthcare Font", 42, true, false, false, false, Font::Antialias::Low);
		distalFmValueLabel.text            = L"---";
		distalFmValueLabel.color           = Palette::Black;
		distalFmValueLabel.horizontalAlign = HAlign::Center;

		separator.position                 = Point(8, 156);
		separator.size                     = Size(240, 8);
		separator.color2                   = Palette::Black;

		ifrTrendLabel.name                 = L"ifrTrendLabel";
		ifrTrendLabel.position             = Point(16, 172);
		ifrTrendLabel.size                 = Size(136, 40);
		ifrTrendLabel.font                 = Font(L"Philips Healthcare Font", 28, false, false, false, false, Font::Antialias::High);
		ifrTrendLabel.text                 = L"";
		ifrTrendLabel.color                = Palette::Black;

		fmTrendValue.name                  = L"fmTrendValue";
		fmTrendValue.position              = Point(160, 172);
		fmTrendValue.size                  = Size(72, 32);
		fmTrendValue.font                  = Font(L"Philips Healthcare Font", 28, false, false, false, false, Font::Antialias::High);
		fmTrendValue.text                  = L"---";
		fmTrendValue.color                 = Palette::Black;
		fmTrendValue.horizontalAlign       = HAlign::Right;

		layoutUpdateEnd();
	}

public:

	Label     fmTypeLabel;
	Label     distalFmValueLabel;
	Separator separator;
	Label     ifrTrendLabel;
	Label     fmTrendValue;

private:

	AlluraIfrReviewPanel(const AlluraIfrReviewPanel&);
	AlluraIfrReviewPanel& operator=(const AlluraIfrReviewPanel&);
};

}}