/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>
#include "Translation.h"

using namespace Sense;
using namespace Sense::ExperienceIdentity;

namespace Pci { namespace Core
{

	class ExportBusyDialog : public Dialog
	{
	public:

		ExportBusyDialog(Control &parent)
			:
			Dialog(parent)
		#pragma region Sense Composer (do not modify)
	,	labelExport      (*this)
	,	progressCircle   (*this)
	,	labelRemaining   (*this)
	,	buttonAbort      (*this)
		#pragma endregion
		{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		//composerLocaleNamespace        = Localization::Translation;
		name                             = L"Transfer in progress";
		size                             = Size(582, 196);
		visible                          = false;
		movable                          = false;
		text                             = Localization::Translation::IDS_ExportBusyTitle;    //L"Transfer in progress";
		labelExport.name                 = L"labelExport";
		labelExport.position             = Point(16, 8);
		labelExport.size                 = Size(480, 64);
		labelExport.text                 = Localization::Translation::IDS_ExportBusy;    //L"DICOM transfer is in progress. Please wait for this transfer to finish.\r\nPress X to return to the application.\r\nPress Abort to stop the transfer (any snapshots or movies that are not yet transferred will be lost).";
		labelExport.textType             = TextType::WordWrap;
		progressCircle.position          = Point(504, 24);
		progressCircle.size              = Size(64, 64);
		progressCircle.determinate       = false;
		labelRemaining.name              = L"labelRemaining";
		labelRemaining.position          = Point(16, 80);
		labelRemaining.size              = Size(480, 24);
		labelRemaining.text              = Localization::Translation::IDS_ExportRemaining;    //L"Items remaining: 999";
		labelRemaining.textType          = TextType::WordWrap;
		buttonAbort.name                 = L"buttonAbort";
		buttonAbort.position             = Point(216, 112);
		buttonAbort.size                 = Size(128, 32);
		buttonAbort.text				 = Localization::Translation::IDS_Abort;
		layoutUpdateEnd();
		#pragma endregion
		}

		void hide()
		{
			visible = false;
		}

		void show()
		{
			auto parentRect = getParentSpace().bounds;
			position = Point((parentRect.width() - size->width) / 2, (parentRect.height() - size->height) / 2);
			visible = true;
		}

	#pragma region Sense Composer (do not modify)
	public:    Label             labelExport;
	private:   ProgressCircle    progressCircle;
	public:    Label             labelRemaining;
	public:    Button            buttonAbort;
	#pragma endregion

		ExportBusyDialog(const ExportBusyDialog&) = delete;
		ExportBusyDialog& operator=(const ExportBusyDialog&) = delete;
	};

}}
