/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>
#include "MenuButtonSmartSuite.h"
#include "PatientBar.h"

namespace Pci { namespace Core
{
using namespace Sense;
using namespace Sense::ExperienceIdentity;

class MainSmartSuite19InchView : public Control
{
public:

	MainSmartSuite19InchView(Control &parent)
	:
		Control(parent)
		#pragma region Sense Composer (do not modify)
	,	side             (*this)
	,	fmDisconnect     (side)
	,	labelCoregInfo   (side)
	,	labelMessageArea2(side)
	,	separator        (side)
	,	separator2       (side)
	,	stbMarkerImage   (side)
	,	labelMessageArea1(side)
	,	main             ((Control&)*this)
	,	panel2           (*this)
	,	systemMenu       (panel2)
	,	helpMenu         (panel2)
	,	tab              (panel2)
	,	tabCoronaryTools (tab)
	,	patientBar       (panel2, PatientBarColorScheme::SmS)
	,	separator3       (*this)
	,	separator4       (*this)
	,	icontrolDisconnectLabel(*this)
		#pragma endregion
	{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		size                             = Size(1280, 1024);
		font                             = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		side.name                        = L"side";
		side.position                    = Point(984, 30);
		side.size                        = Size(296, 994);
		side.border                      = Margin(0, 0, 0, 0);
		side.edge                        = Margin(0, 0, 0, 0);
		side.color                       = Color::fromRgb(0, 0, 0);
		fmDisconnect.name                = L"fmDisconnect";
		fmDisconnect.position            = Point(248, 962);
		fmDisconnect.size                = Size(32, 32);
		fmDisconnect.image               = Icons::RemoteConnectivityOff;
		labelCoregInfo.name              = L"labelCoregInfo";
		labelCoregInfo.position          = Point(4, 728);
		labelCoregInfo.size              = Size(288, 90);
		labelCoregInfo.font              = Font(L"Philips Healthcare Font", 18, false, false, false, false, Font::Antialias::High);
		labelCoregInfo.text              = L"Unreliable connection.......";
		labelCoregInfo.textType          = TextType::WordWrap;
		labelCoregInfo.color             = Palette::Gray070;
		labelCoregInfo.outline           = Palette::Black;
		labelCoregInfo.verticalAlign     = VAlign::Middle;
		labelMessageArea2.name           = L"labelMessageArea2";
		labelMessageArea2.position       = Point(4, 883);
		labelMessageArea2.size           = Size(288, 75);
		labelMessageArea2.font           = Font(L"Philips Healthcare Font", 18, false, false, false, false, Font::Antialias::High);
		labelMessageArea2.text           = L"Use the TSM to create a snapshot or movie";
		labelMessageArea2.textType       = TextType::WordWrap;
		labelMessageArea2.color          = Palette::Gray070;
		labelMessageArea2.outline        = Palette::Black;
		labelMessageArea2.verticalAlign  = VAlign::Middle;
		separator.name                   = L"separator";
		separator.position               = Point(4, 958);
		separator.size                   = Size(288, 2);
		separator.color1                 = Palette::Gray150;
		separator.color2                 = Palette::Transparent;
		separator2.name                  = L"separator2";
		separator2.position              = Point(4, 726);
		separator2.size                  = Size(288, 2);
		separator2.color1                = Palette::Gray150;
		separator2.color2                = Palette::Transparent;
		stbMarkerImage.name              = L"stbMarkerImage";
		stbMarkerImage.position          = Point(4, 4);
		stbMarkerImage.size              = Size(290, 290);
		labelMessageArea1.name           = L"labelMessageArea1";
		labelMessageArea1.position       = Point(4, 818);
		labelMessageArea1.size           = Size(288, 88);
		labelMessageArea1.font           = Font(L"Philips Healthcare Font", 18, false, false, false, false, Font::Antialias::High);
		labelMessageArea1.text           = L"Use the TSM to create a snapshot or movie . Use the TSM to create a snapshot or movie a snapshot or movie ";
		labelMessageArea1.textType       = TextType::WordWrap;
		labelMessageArea1.color          = Palette::Gray070;
		labelMessageArea1.outline        = Palette::Black;
		labelMessageArea1.verticalAlign  = VAlign::Middle;
		main.name                        = L"main";
		main.position                    = Point(2, 32);
		main.size                        = Size(982, 992);
		panel2.name                      = L"panel2";
		panel2.size                      = Size(1280, 30);
		panel2.border                    = Margin(0, 0, 0, 0);
		panel2.edge                      = Margin(0, 0, 0, 0);
		panel2.color                     = Color::fromRgb(0, 0, 0);
		//systemMenu.composerClass       = Control;
		systemMenu.name                  = L"systemMenu";
		systemMenu.position              = Point(1120, 0);
		systemMenu.size                  = Size(80, 30);
		systemMenu.font                  = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		//helpMenu.composerClass         = Control;
		helpMenu.name                    = L"helpMenu";
		helpMenu.position                = Point(1200, 0);
		helpMenu.size                    = Size(80, 30);
		helpMenu.font                    = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		tab.name                         = L"tab";
		tab.position                     = Point(8, 0);
		tab.size                         = Size(256, 30);
		tab.font                         = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		tab.headerWidth                  = 230;
		tab.headerHeight                 = 30;
		tab.headerImageSize              = Size(22, 22);
		tabCoronaryTools.name            = L"tabCoronaryTools";
		tabCoronaryTools.text            = L"Coronary Tools";
		tabCoronaryTools.image           = Icons::HeartSegmentation;
		//patientBar.composerClass       = Control;
		patientBar.name                  = L"PatientBar";
		patientBar.position              = Point(302, 0);
		patientBar.size                  = Size(682, 30);
		patientBar.font                  = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		separator3.name                  = L"separator3";
		separator3.position              = Point(0, 29);
		separator3.size                  = Size(1280, 2);
		separator3.color1                = Palette::Gray150;
		separator3.color2                = Palette::Transparent;
		separator4.name                  = L"separator4";
		separator4.position              = Point(984, 30);
		separator4.size                  = Size(2, 994);
		separator4.color1                = Palette::Gray150;
		separator4.color2                = Palette::Transparent;
		separator4.orientation           = Orientation::Vertical;
		icontrolDisconnectLabel.name     = L"icontrolDisconnectLabel";
		icontrolDisconnectLabel.position = Point(1192, 992);
		icontrolDisconnectLabel.size     = Size(32, 32);
		icontrolDisconnectLabel.text     = L"";
		icontrolDisconnectLabel.image    = Icons::ConnectionWarning;
		layoutUpdateEnd();
		#pragma endregion
	}

	#pragma region Sense Composer (do not modify)
	public:    Panel             side;
	public:    Label             fmDisconnect;
	public:    Label             labelCoregInfo;
	public:    Label             labelMessageArea2;
	public:    Separator         separator;
	public:    Separator         separator2;
	public:    Control           stbMarkerImage;
	public:    Label             labelMessageArea1;
	public:    Control           main;
	public:    Panel             panel2;
	public:    MenuButtonSmartSuite systemMenu;
	public:    MenuButtonSmartSuite helpMenu;
	public:    TabButtonBar      tab;
	public:    TabButton         tabCoronaryTools;
	public:    PatientBar        patientBar;
	public:    Separator         separator3;
	public:    Separator         separator4;
	public:    Label             icontrolDisconnectLabel;
	#pragma endregion

private:

	MainSmartSuite19InchView(const MainSmartSuite19InchView&);
	MainSmartSuite19InchView& operator=(const MainSmartSuite19InchView&);
};

}}
