/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>
#include "MenuButtonSmartSuite.h"
#include "PatientBar.h"

namespace Pci { namespace Core
{
using namespace Sense;
using namespace Sense::ExperienceIdentity;

class MainSmartSuiteFlexVisionView : public Control
{
public:

	MainSmartSuiteFlexVisionView(Control &parent)
	:
		Control(parent)
		#pragma region Sense Composer (do not modify)
	,	side             (*this)
	,	separator2       (side)
	,	stbMarkerImage   (side)
	,	fmDisconnect     (side)
	,	labelCoregInfo   (side)
	,	labelMessageArea2(side)
	,	separator        (side)
	,	labelMessageArea1(side)
	,	icontrolDisconnectLabel(side)
	,	main             ((Control&)*this)
	,	panel2           (*this)
	,	systemMenu       (panel2)
	,	helpMenu         (panel2)
	,	tab              (panel2)
	,	tabCoronaryTools (tab)
	,	patientBar       (panel2, PatientBarColorScheme::SmS)
	,	separator3       (*this)
	,	separator4       (*this)
		#pragma endregion
	{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		size                             = Size(1280, 990);
		font                             = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		side.name                        = L"side";
		side.position                    = Point(960, 30);
		side.size                        = Size(314, 960);
		side.border                      = Margin(0, 0, 0, 0);
		side.edge                        = Margin(0, 0, 0, 0);
		side.color                       = Color::fromRgb(0, 0, 0);
		separator2.name                  = L"separator2";
		separator2.position              = Point(4, 692);
		separator2.size                  = Size(312, 2);
		separator2.color1                = Palette::Gray150;
		separator2.color2                = Palette::Transparent;
		stbMarkerImage.name              = L"stbMarkerImage";
		stbMarkerImage.position          = Point(4, 4);
		stbMarkerImage.size              = Size(312, 312);
		fmDisconnect.name                = L"fmDisconnect";
		fmDisconnect.position            = Point(272, 928);
		fmDisconnect.size                = Size(32, 32);
		fmDisconnect.image               = Icons::RemoteConnectivityOff;
		labelCoregInfo.name              = L"labelCoregInfo";
		labelCoregInfo.position          = Point(4, 694);
		labelCoregInfo.size              = Size(312, 90);
		labelCoregInfo.font              = Font(L"Philips Healthcare Font", 18, false, false, false, false, Font::Antialias::High);
		labelCoregInfo.text              = L"Unreliable connection.......";
		labelCoregInfo.textType          = TextType::WordWrap;
		labelCoregInfo.color             = Palette::Gray070;
		labelCoregInfo.outline           = Palette::Black;
		labelCoregInfo.verticalAlign     = VAlign::Middle;
		labelMessageArea2.name           = L"labelMessageArea2";
		labelMessageArea2.position       = Point(4, 854);
		labelMessageArea2.size           = Size(312, 70);
		labelMessageArea2.font           = Font(L"Philips Healthcare Font", 18, false, false, false, false, Font::Antialias::High);
		labelMessageArea2.text           = L"Use the TSM to create a snapshot or movie";
		labelMessageArea2.textType       = TextType::WordWrap;
		labelMessageArea2.color          = Palette::Gray070;
		labelMessageArea2.outline        = Palette::Black;
		labelMessageArea2.verticalAlign  = VAlign::Middle;
		separator.name                   = L"separator";
		separator.position               = Point(4, 924);
		separator.size                   = Size(312, 2);
		separator.color1                 = Palette::Gray150;
		separator.color2                 = Palette::Transparent;
		labelMessageArea1.name           = L"labelMessageArea1";
		labelMessageArea1.position       = Point(4, 784);
		labelMessageArea1.size           = Size(312, 93);
		labelMessageArea1.font           = Font(L"Philips Healthcare Font", 18, false, false, false, false, Font::Antialias::High);
		labelMessageArea1.text           = L"Use the TSM to create a snapshot or movie . Use the TSM to create a snapshot or movie ";
		labelMessageArea1.textType       = TextType::WordWrap;
		labelMessageArea1.color          = Palette::Gray070;
		labelMessageArea1.outline        = Palette::Black;
		labelMessageArea1.verticalAlign  = VAlign::Middle;
		icontrolDisconnectLabel.name     = L"icontrolDisconnectLabel";
		icontrolDisconnectLabel.position = Point(232, 928);
		icontrolDisconnectLabel.size     = Size(32, 32);
		icontrolDisconnectLabel.text     = L"";
		icontrolDisconnectLabel.image    = Icons::ConnectionWarning;
		main.name                        = L"main";
		main.position                    = Point(0, 32);
		main.size                        = Size(956, 956);
		panel2.name                      = L"panel2";
		panel2.size                      = Size(1280, 30);
		panel2.border                    = Margin(0, 0, 0, 0);
		panel2.edge                      = Margin(0, 0, 0, 0);
		panel2.color                     = Color::fromRgb(0, 0, 0);
		//systemMenu.composerClass       = Control;
		systemMenu.name                  = L"systemMenu";
		systemMenu.position              = Point(1120, 0);
		systemMenu.size                  = Size(80, 30);
		systemMenu.font                  = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		//helpMenu.composerClass         = Control;
		helpMenu.name                    = L"helpMenu";
		helpMenu.position                = Point(1200, 0);
		helpMenu.size                    = Size(80, 30);
		helpMenu.font                    = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		tab.name                         = L"tab";
		tab.position                     = Point(8, 0);
		tab.size                         = Size(256, 30);
		tab.font                         = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		tab.headerWidth                  = 230;
		tab.headerHeight                 = 30;
		tab.headerImageSize              = Size(22, 22);
		tabCoronaryTools.name            = L"tabCoronaryTools";
		tabCoronaryTools.text            = L"Coronary Tools";
		tabCoronaryTools.image           = Icons::HeartSegmentation;
		//patientBar.composerClass       = Control;
		patientBar.name                  = L"PatientBar";
		patientBar.position              = Point(302, 0);
		patientBar.size                  = Size(658, 30);
		patientBar.font                  = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		separator3.name                  = L"separator3";
		separator3.position              = Point(0, 29);
		separator3.size                  = Size(1280, 2);
		separator3.color1                = Palette::Gray150;
		separator3.color2                = Palette::Transparent;
		separator4.name                  = L"separator4";
		separator4.position              = Point(960, 30);
		separator4.size                  = Size(2, 960);
		separator4.color1                = Palette::Gray150;
		separator4.color2                = Palette::Transparent;
		separator4.orientation           = Orientation::Vertical;
		layoutUpdateEnd();
		#pragma endregion
	}

	#pragma region Sense Composer (do not modify)
	public:    Panel             side;
	public:    Separator         separator2;
	public:    Control           stbMarkerImage;
	public:    Label             fmDisconnect;
	public:    Label             labelCoregInfo;
	public:    Label             labelMessageArea2;
	public:    Separator         separator;
	public:    Label             labelMessageArea1;
	public:    Label             icontrolDisconnectLabel;
	public:    Control           main;
	public:    Panel             panel2;
	public:    MenuButtonSmartSuite systemMenu;
	public:    MenuButtonSmartSuite helpMenu;
	public:    TabButtonBar      tab;
	public:    TabButton         tabCoronaryTools;
	public:    PatientBar        patientBar;
	public:    Separator         separator3;
	public:    Separator         separator4;
	#pragma endregion

private:

	MainSmartSuiteFlexVisionView(const MainSmartSuiteFlexVisionView&);
	MainSmartSuiteFlexVisionView& operator=(const MainSmartSuiteFlexVisionView&);
};

}}
