// ********************* WARNING *****************************
// * This file was automatically generated by Sense Composer *
// *      Modifying this file manually is frowned upon       *
// ***********************************************************
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>

namespace Pci { namespace Core { namespace UI
{

using namespace Sense;
using namespace Sense::ExperienceIdentity;

class PciXrayGeometryControlUi : public Control
{
public:

	PciXrayGeometryControlUi(Control &parent)
	:
		Control              (parent),
		layout2              (*this),
		labelRotationName    (layout2),
		labelAngulationName  (layout2),
		valuePanel           (*this),
		labelRotationValue   (valuePanel),
		labelAngulationValue (valuePanel)
	{
		layoutUpdateBegin();

		name                                 = L"CrmPosition";
		size                                 = Size(165, 72);
		font                                 = Font(L"Philips Healthcare Font", 28, false, false, false, false, Font::Antialias::None);
		layoutSpacing                        = 0;
		layoutOrientation                    = Orientation::Horizontal;

		layout2.size                         = Size(90, 72);
		layout2.layout                       = Layout::Fixed1d;
		layout2.layoutSpacing                = 0;

		labelRotationName.size               = Size(90, 36);
		labelRotationName.layout             = Layout::Fill;
		labelRotationName.text               = L"RAO";
		labelRotationName.outline            = Palette::Black;
		labelRotationName.verticalAlign      = VAlign::Middle;

		labelAngulationName.position         = Point(0, 36);
		labelAngulationName.size             = Size(90, 36);
		labelAngulationName.layout           = Layout::Fill;
		labelAngulationName.text             = L"CRAN";
		labelAngulationName.outline          = Palette::Black;
		labelAngulationName.verticalAlign    = VAlign::Middle;

		valuePanel.position                  = Point(90, 0);
		valuePanel.size                      = Size(75, 72);
		valuePanel.layout                    = Layout::Fill;
		valuePanel.layoutSpacing             = 0;

		labelRotationValue.size              = Size(75, 36);
		labelRotationValue.layout            = Layout::Fill;
		labelRotationValue.text              = L"0°";
		labelRotationValue.outline           = Palette::Black;
		labelRotationValue.horizontalAlign   = HAlign::Right;
		labelRotationValue.verticalAlign     = VAlign::Middle;

		labelAngulationValue.position        = Point(0, 36);
		labelAngulationValue.size            = Size(75, 36);
		labelAngulationValue.layout          = Layout::Fill;
		labelAngulationValue.text            = L"0°";
		labelAngulationValue.outline         = Palette::Black;
		labelAngulationValue.horizontalAlign = HAlign::Right;
		labelAngulationValue.verticalAlign   = VAlign::Middle;

		layoutUpdateEnd();
	}

public:

	Spacer		  layout2;
	Label         labelRotationName;
	Label         labelAngulationName;
	Spacer        valuePanel;
	Label         labelRotationValue;
	Label         labelAngulationValue;

private:

	PciXrayGeometryControlUi(const PciXrayGeometryControlUi&);
	PciXrayGeometryControlUi& operator=(const PciXrayGeometryControlUi&);
};

}}}