/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>

#include "StbMarkersViewer.h"
#include "ViewType.h"

using namespace Sense;
using namespace Sense::ExperienceIdentity;

using  namespace Pci::Core;

namespace Pci { namespace Core { namespace UI
{

class PictorialItem : public Control
{
public:
	PictorialItem(Control &parent)
	:
		Control(parent)
		#pragma region Sense Composer (do not modify)
	,	panel            (*this)
	,	imageBox         (panel)
	,	lockIcon         (imageBox)
	,	pictorialLabel (*this)
		#pragma endregion
	{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		//composerReference              = C:\Users\320024878\Pictures\SelectFramething.png;
		size                             = Size(160, 190);
		layoutSpacing                    = 0;
		panel.name                       = L"panel";
		panel.size                       = Size(160, 160);
		panel.layout                     = Layout::Fixed1d;
		panel.layoutSpacing              = 0;
		panel.radius                     = Corners(4, 4, 4, 4);
		panel.border                     = Margin(3, 3, 3, 3);
		panel.edge                       = Margin(0, 0, 0, 0);
		panel.colorBorder                = Palette::Yellow070;
		panel.colorEdge                  = Palette::Transparent * 0.00;
		panel.color                      = Palette::Black;
		//imageBox.composerClass         = Control;
		imageBox.name                    = L"imageBox";
		imageBox.size                    = Size(154, 154);
		imageBox.layout                  = Layout::Fill;
		lockIcon.name                    = L"lockIcon";
		lockIcon.position                = Point(0, 10);
		lockIcon.size                    = Size(144, 24);
		lockIcon.visible                 = false;
		lockIcon.layoutOuterMargin       = Margin(0, 10, 10, 0);
		lockIcon.text                    = L"";
		lockIcon.horizontalAlign         = HAlign::Right;
		lockIcon.verticalAlign           = VAlign::Middle;
		lockIcon.image                   = Icons::GeneralLock;
		lockIcon.imageSize               = Size(24, 24);
		lockIcon.imagePosition           = ImagePosition::Right;
		pictorialLabel.name            = L"imageNumberLabel";
		pictorialLabel.position        = Point(0, 168);
		pictorialLabel.size            = Size(160, 22);
		pictorialLabel.font            = Font(L"Philips Healthcare Font", 18, false, false, false, false, Font::Antialias::High);
		pictorialLabel.layout          = Layout::Fixed1d;
		pictorialLabel.layoutOuterMargin = Margin(0, 8, 0, 0);
		pictorialLabel.text            = L"44";
		pictorialLabel.color           = Palette::Yellow060;
		pictorialLabel.horizontalAlign = HAlign::Center;
		pictorialLabel.verticalAlign   = VAlign::Middle;
		pictorialLabel.imageSize       = Size(0, 0);
		pictorialLabel.imageSpacing    = 0;
		layoutUpdateEnd();
		#pragma endregion
	}

	#pragma region Sense Composer (do not modify)
	public:    Panel             panel;
	public:    Buffer            imageBox;
	public:    Label             lockIcon;
	public:    Label             pictorialLabel;
	#pragma endregion

private:

	PictorialItem(const PictorialItem&);
	PictorialItem& operator=(const PictorialItem&);
};

}}}
