/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>

namespace Pci { namespace Core
{
using namespace Sense;
using namespace Sense::ExperienceIdentity;

class ProblemReportDialogUi : public Dialog
{
public:

	ProblemReportDialogUi(Control &parent)
	:
		Dialog(parent)
		#pragma region Sense Composer (do not modify)
	,	closeButton      (*this)
	,	message          (*this)
	,	contactService   (*this)
		#pragma endregion
	{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		name                             = L"ProblemReportDialogUi";
		size                             = Size(358, 164);
		font                             = Font(L"Philips Healthcare Font", 12, false, false, false, false, Font::Antialias::High);
		text                             = L"Problem report";
		closeButton.name                 = L"closeButton";
		closeButton.position             = Point(112, 80);
		closeButton.size                 = Size(128, 32);
		closeButton.font                 = Font(L"Philips Healthcare Font", 12, false, false, false, false, Font::Antialias::High);
		closeButton.text                 = L"OK";
		message.name                     = L"message";
		message.position                 = Point(8, 8);
		message.size                     = Size(336, 32);
		message.font                     = Font(L"Philips Healthcare Font", 12, true, false, false, false, Font::Antialias::High);
		message.text                     = L"PROBLEM_REPORT_READY";
		message.horizontalAlign          = HAlign::Center;
		message.verticalAlign            = VAlign::Middle;
		contactService.name              = L"contactService";
		contactService.position          = Point(8, 40);
		contactService.size              = Size(336, 32);
		contactService.font              = Font(L"Philips Healthcare Font", 12, true, false, false, false, Font::Antialias::High);
		contactService.text              = L"CONTACT_SERVICE_PROVIDER";
		contactService.horizontalAlign   = HAlign::Center;
		contactService.verticalAlign     = VAlign::Middle;
		layoutUpdateEnd();
		#pragma endregion
	}

	#pragma region Sense Composer (do not modify)
	public:    Button            closeButton;
	public:    Label             message;
	public:    Label             contactService;
	#pragma endregion

private:

	ProblemReportDialogUi(const ProblemReportDialogUi&);
	ProblemReportDialogUi& operator=(const ProblemReportDialogUi&);
};

}}
