/*----------------------------------------------------
 |      This file was generated by Res2Sense 2.0     |
 |              Do not modify this file.             |
 ----------------------------------------------------*/

#pragma once

#include <Sense.h>

namespace PciSuite { 

class Resources
{
public:

	static const Sense::Image About_template_800;
	static const Sense::Image apc_3dapc;
	static const Sense::Image ApplicationCoronaryTools_SmS;
	static const Sense::Image BatchCode;
	static const Sense::Image CE;
	static const Sense::Image CE_UKCA;
	static const Sense::Image CELogo_allura;
	static const Sense::Image CELogo_azurion;
	static const Sense::Image crmstartscreen_guidance_catheter;
	static const Sense::Image ffrReview;
	static const Sense::Image Icon_StbLive;
	static const Sense::Image Icon_StbPostDeployment;
	static const Sense::Image Icon_StbSubtract;
	static const Sense::Image IfrReview;
	static const Sense::Image IfuLight;
	static const Sense::Image ImageIndicatorLih;
	static const Sense::Image indicator_lih;
	static const Sense::Image Licence_agreement_template;
	static const Sense::Image manufacturer_black;
	static const Sense::Image manufacturer_gray;
	static const Sense::Image MDR_MDMarking;
	static const Sense::Image MDR_UDIMarking;
	static const Sense::Image ModelNumber;
	static const Sense::Image PatientAcquisitionIxr;
	static const Sense::Image PCITools_startscreen_guidance_epx;
	static const Sense::Image pedals_fluoro;
	static const Sense::Image PhilipsShield;
	static const Sense::Image StatusPhysiologyConnected;
	static const Sense::Image StatusPhysiologyDisconnected;
	static const Sense::Image stentboost_guidance_markers_collimation;
	static const Sense::Image ThumbPreview;
	static const Sense::Image tso_acc;
	static const Sense::Image tso_acc_SmS;
	static const Sense::Image UKCA;
	static const Sense::Image warning;
	static const Sense::Image XrayRotational140x140;
	static const Sense::Image XraySettings140x140;
	static const unsigned char eula_dynamic_coronary_roadmap[620];
	static const unsigned char eula_stentboost_live[620];
	
	struct ImageDescription
	{
		const wchar_t *name;
		const Sense::Image *image;
	};
	
	static const ImageDescription imageList[37];
	
	struct DataDescription
	{
		const wchar_t *name;
		const unsigned char * data;
		const int length;
	};
	
	static const DataDescription dataList[2];

};

} 