/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>

namespace Pci { namespace Core { namespace UI
{
using namespace Sense;
using namespace Sense::ExperienceIdentity;

class SmartSuiteEpxSelectionUi : public Control
{
public:

	SmartSuiteEpxSelectionUi(Control &parent)
	:
		Control(parent)
		#pragma region Sense Composer (do not modify)
	,	spacer           (*this)
	,	spacer2          (*this)
	,	separator        (spacer2)
	,	panelMessage     (spacer2)
	,	control          (panelMessage)
	,	picture          (control)
	,	labelAcquisition (picture)
	,	control2         (panelMessage)
	,	labelMessage     (control2)
	,	separator2       (spacer2)
		#pragma endregion
	{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		name                             = L"SmartSuiteEpxSelectionUi";
		size                             = Size(952, 952);
		spacer.size                      = Size(952, 564);
		spacer.layoutUseSpacing          = false;
		spacer.layout                    = Layout::Fill;
		spacer2.position                 = Point(0, 564);
		spacer2.size                     = Size(952, 388);
		spacer2.layout                   = Layout::Fixed1d;
		separator.position               = Point(5, 0);
		separator.size                   = Size(942, 2);
		separator.layout                 = Layout::Fixed1d;
		separator.layoutOuterMargin      = Margin(5, 0, 5, 0);
		separator.color1                 = Palette::Gray150;
		separator.color2                 = Palette::Transparent * 0.00;
		panelMessage.name                = L"panelMessage";
		panelMessage.position            = Point(0, 2);
		panelMessage.size                = Size(952, 304);
		panelMessage.layoutUseSpacing    = false;
		panelMessage.layout              = Layout::Fixed1d;
		panelMessage.layoutSpacing       = 0;
		panelMessage.layoutOrientation   = Orientation::Horizontal;
		panelMessage.border              = Margin(0, 0, 0, 0);
		panelMessage.edge                = Margin(0, 0, 0, 0);
		panelMessage.colorBorder         = Color::fromRgb(183, 178, 168);
		panelMessage.color               = Palette::Transparent * 0.00;
		control.name                     = L"control";
		control.size                     = Size(164, 304);
		control.layout                   = Layout::Fixed1d;
		picture.name                     = L"picture";
		picture.position                 = Point(16, 24);
		picture.size                     = Size(140, 140);
		labelAcquisition.name            = L"labelAcquisition";
		labelAcquisition.position        = Point(0, 60);
		labelAcquisition.size            = Size(140, 40);
		labelAcquisition.font            = Font(L"Philips Healthcare Font", 20, true, false, false, false, Font::Antialias::High);
		labelAcquisition.text            = L"Acquisition";
		labelAcquisition.horizontalAlign = HAlign::Center;
		labelAcquisition.verticalAlign   = VAlign::Middle;
		control2.name                    = L"control2";
		control2.position                = Point(180, 16);
		control2.size                    = Size(764, 272);
		control2.layout                  = Layout::Fill;
		control2.layoutOuterMargin       = Margin(16, 16, 8, 16);
		labelMessage.name                = L"labelMessage";
		labelMessage.size                = Size(764, 272);
		labelMessage.font                = Font(L"Philips Healthcare Font", 32, true, false, false, false, Font::Antialias::High);
		labelMessage.layout              = Layout::Fill;
		labelMessage.text                = L"Activate Dynamic Coronary Roadmap or StentBoost Live by selecting the appropriate acquisition protocol on the touchscreen";
		labelMessage.textType            = TextType::WordWrap;
		labelMessage.color               = Palette::Gray070;
		labelMessage.outline             = Palette::Black;
		separator2.position              = Point(5, 306);
		separator2.size                  = Size(942, 2);
		separator2.layout                = Layout::Fixed1d;
		separator2.layoutOuterMargin     = Margin(5, 0, 5, 0);
		separator2.color1                = Palette::Gray150;
		separator2.color2                = Palette::Transparent * 0.00;
		layoutUpdateEnd();
		#pragma endregion
	}

	#pragma region Sense Composer (do not modify)
	private:   Spacer            spacer;
	private:   Spacer            spacer2;
	private:   Separator         separator;
	public:    Panel             panelMessage;
	public:    Control           control;
	public:    PictureBox        picture;
	public:    Label             labelAcquisition;
	public:    Control           control2;
	public:    Label             labelMessage;
	private:   Separator         separator2;
	#pragma endregion

private:

	SmartSuiteEpxSelectionUi(const SmartSuiteEpxSelectionUi&);
	SmartSuiteEpxSelectionUi& operator=(const SmartSuiteEpxSelectionUi&);
};

}}}
