// ********************* WARNING *****************************
// * This file was automatically generated by Sense Composer *
// *      Modifying this file manually is frowned upon       *
// ***********************************************************
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>
#include "SmartSuiteFullHDIfrReviewPanel.ui.h"
#include "PciProgressBar.h"

namespace Pci { namespace Core
{

using namespace Sense;
using namespace Sense::ExperienceIdentity;

class SmartSuiteFullHDCoregUi : public Control
{
public:

	SmartSuiteFullHDCoregUi(Control &parent)
	:
		Control              (parent),
		panelPopup           (*this),
		popupPanelHeader     ((Control&)panelPopup),
		popupPanelHeaderText (popupPanelHeader),
		topLayOutPannel      ((Control&)panelPopup),
		panelValues          (topLayOutPannel),
		firstRowPanel        (panelValues),
		panelPaNames         (firstRowPanel),
		labelPa              (panelPaNames),
		labelPaValue         (panelPaNames),
		panelPaPdNames       ((Control&)firstRowPanel),
		labelPdPa            (panelPaPdNames),
		labelPdPaValue       (panelPaPdNames),
		secontRowPanel       (panelValues),
		panelPdNames         (secontRowPanel),
		labelPd              (panelPdNames),
		labelPdValue         (panelPdNames),
		paneliFrFfrNames     ((Control&)secontRowPanel),
		labeliFRfFR          (paneliFrFfrNames),
		labeliFRfFRValue     (paneliFrFfrNames),
		progressPanel        ((Control&)paneliFrFfrNames),
		progress             (progressPanel),
		ifrReviewPanel       (topLayOutPannel),
		ifrSpotReviewPanel   ((Control&)topLayOutPannel),
		labeliFrSpot         (ifrSpotReviewPanel),
		labeliFrSpotValue    (ifrSpotReviewPanel),
		graphLayoutPanel     (*this),
		graphPanel           (graphLayoutPanel)
	{
		layoutUpdateBegin();

		size                               = Size(960, 960);

		panelPopup.size                    = Size(960, 960);
		panelPopup.layout                  = Layout::Fill;
		panelPopup.layoutSpacing           = 0;
		panelPopup.radius                  = Corners(5, 5, 5, 5);
		panelPopup.border                  = Margin(0, 0, 0, 0);
		panelPopup.edge                    = Margin(1, 1, 1, 1);

		popupPanelHeader.size              = Size(958, 24);
		popupPanelHeader.layout            = Layout::Fixed1d;
		popupPanelHeader.layoutUseSpacing  = false;
		popupPanelHeader.layoutOuterMargin = Margin(8, 2, 2, 2);
		popupPanelHeader.layoutSpacing     = 0;
		popupPanelHeader.radius            = Corners(5, 5, 0, 0);
		popupPanelHeader.border            = Margin(0, 0, 0, 0);
		popupPanelHeader.edge              = Margin(0, 0, 0, 0);

		popupPanelHeaderText.position      = Point(8, 2);
		popupPanelHeaderText.size          = Size(948, 20);
		popupPanelHeaderText.font          = Font(L"Philips Healthcare Font", 15, false, false, false, false, Font::Antialias::High);
		popupPanelHeaderText.layout        = Layout::Fill;
		popupPanelHeaderText.text          = L"Header";
		popupPanelHeaderText.color         = Palette::Yellow050;
		popupPanelHeaderText.verticalAlign = VAlign::Middle;
		popupPanelHeaderText.image         = Icons::WaveformShowHide;

		topLayOutPannel.name               = L"TopLayOutPanel";
		topLayOutPannel.position           = Point(268, 50);
		topLayOutPannel.size               = Size(400, 94);
		topLayOutPannel.border             = Margin(0, 0, 0, 0);
		topLayOutPannel.edge               = Margin(0, 0, 0, 0);

		panelValues.size                   = Size(400, 26);
		panelValues.layout                 = Layout::Fill;
		panelValues.layoutSpacing          = 0;

		firstRowPanel.name                 = L"firstRowPanel";
		firstRowPanel.size                 = Size(400, 13);
		firstRowPanel.layout               = Layout::Fill;
		firstRowPanel.layoutOuterMargin    = Margin(8, 0, 8, 0);
		firstRowPanel.layoutSpacing        = 0;
		firstRowPanel.layoutOrientation    = Orientation::Horizontal;
		firstRowPanel.border               = Margin(0, 0, 0, 0);
		firstRowPanel.edge                 = Margin(0, 0, 0, 0);

		panelPaNames.position              = Point(8, 0);
		panelPaNames.size                  = Size(192, 13);
		panelPaNames.layout                = Layout::Fill;
		panelPaNames.layoutOuterMargin     = Margin(0, 0, 50, 0);
		panelPaNames.layoutSpacing         = 0;
		panelPaNames.layoutOrientation     = Orientation::Horizontal;

		labelPa.size                       = Size(71, 13);
		labelPa.font                       = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labelPa.layout                     = Layout::Fill;
		labelPa.text                       = L"Pa";
		labelPa.color                      = Palette::Red050;
		labelPa.verticalAlign              = VAlign::Middle;

		labelPaValue.position              = Point(71, 0);
		labelPaValue.size                  = Size(71, 13);
		labelPaValue.font                  = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labelPaValue.layout                = Layout::Fill;
		labelPaValue.text                  = L"74";
		labelPaValue.color                 = Palette::Red050;
		labelPaValue.horizontalAlign       = HAlign::Right;
		labelPaValue.verticalAlign         = VAlign::Middle;

		panelPaPdNames.position            = Point(200, 0);
		panelPaPdNames.size                = Size(192, 13);
		panelPaPdNames.layout              = Layout::Fill;
		panelPaPdNames.layoutSpacing       = 0;
		panelPaPdNames.layoutOrientation   = Orientation::Horizontal;
		panelPaPdNames.border              = Margin(0, 0, 0, 0);
		panelPaPdNames.edge                = Margin(0, 0, 0, 0);

		labelPdPa.size                     = Size(96, 13);
		labelPdPa.font                     = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labelPdPa.layout                   = Layout::Fill;
		labelPdPa.text                     = L"Pd/Pa";
		labelPdPa.color                    = Palette::Gray070;
		labelPdPa.verticalAlign            = VAlign::Middle;

		labelPdPaValue.position            = Point(96, 0);
		labelPdPaValue.size                = Size(96, 13);
		labelPdPaValue.font                = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labelPdPaValue.layout              = Layout::Fill;
		labelPdPaValue.text                = L"0.85";
		labelPdPaValue.color               = Palette::Gray070;
		labelPdPaValue.horizontalAlign     = HAlign::Right;
		labelPdPaValue.verticalAlign       = VAlign::Middle;

		secontRowPanel.name                = L"SecontRowPanel";
		secontRowPanel.position            = Point(0, 13);
		secontRowPanel.size                = Size(400, 13);
		secontRowPanel.layout              = Layout::Fill;
		secontRowPanel.layoutOuterMargin   = Margin(8, 0, 8, 0);
		secontRowPanel.layoutSpacing       = 0;
		secontRowPanel.layoutOrientation   = Orientation::Horizontal;
		secontRowPanel.border              = Margin(0, 0, 0, 0);
		secontRowPanel.edge                = Margin(0, 0, 0, 0);

		panelPdNames.position              = Point(8, 0);
		panelPdNames.size                  = Size(192, 13);
		panelPdNames.layout                = Layout::Fill;
		panelPdNames.layoutOuterMargin     = Margin(0, 0, 50, 0);
		panelPdNames.layoutSpacing         = 0;
		panelPdNames.layoutOrientation     = Orientation::Horizontal;

		labelPd.size                       = Size(71, 13);
		labelPd.font                       = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labelPd.layout                     = Layout::Fill;
		labelPd.text                       = L"Pd";
		labelPd.verticalAlign              = VAlign::Middle;

		labelPdValue.position              = Point(71, 0);
		labelPdValue.size                  = Size(71, 13);
		labelPdValue.font                  = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labelPdValue.layout                = Layout::Fill;
		labelPdValue.text                  = L"69";
		labelPdValue.horizontalAlign       = HAlign::Right;
		labelPdValue.verticalAlign         = VAlign::Middle;

		paneliFrFfrNames.position          = Point(200, 0);
		paneliFrFfrNames.size              = Size(192, 13);
		paneliFrFfrNames.layout            = Layout::Fill;
		paneliFrFfrNames.layoutSpacing     = 0;
		paneliFrFfrNames.layoutOrientation = Orientation::Horizontal;
		paneliFrFfrNames.border            = Margin(0, 0, 0, 0);
		paneliFrFfrNames.edge              = Margin(0, 0, 0, 0);

		labeliFRfFR.size                   = Size(64, 13);
		labeliFRfFR.font                   = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labeliFRfFR.layout                 = Layout::Fill;
		labeliFRfFR.text                   = L"iFR";
		labeliFRfFR.color                  = Palette::Gray070;
		labeliFRfFR.verticalAlign          = VAlign::Middle;

		labeliFRfFRValue.position          = Point(64, 0);
		labeliFRfFRValue.size              = Size(64, 13);
		labeliFRfFRValue.font              = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labeliFRfFRValue.layout            = Layout::Fill;
		labeliFRfFRValue.text              = L"0.85";
		labeliFRfFRValue.color             = Palette::Gray070;
		labeliFRfFRValue.horizontalAlign   = HAlign::Right;
		labeliFRfFRValue.verticalAlign     = VAlign::Middle;

		progressPanel.position             = Point(128, 0);
		progressPanel.size                 = Size(64, 13);
		progressPanel.layout               = Layout::Fill;
		progressPanel.layoutSpacing        = 0;
		progressPanel.border               = Margin(4, 18, 4, 18);
		progressPanel.edge                 = Margin(0, 0, 0, 0);

		progress.size                      = Size(56, -23);
		progress.layout                    = Layout::Fill;
		progress.layoutOrientation         = Orientation::Horizontal;

		ifrReviewPanel.name                = L"ifrReviewPanel";
		ifrReviewPanel.position            = Point(0, 34);
		ifrReviewPanel.size                = Size(400, 26);
		ifrReviewPanel.layout              = Layout::Fill;

		ifrSpotReviewPanel.position        = Point(0, 68);
		ifrSpotReviewPanel.size            = Size(400, 26);
		ifrSpotReviewPanel.layout          = Layout::Fill;
		ifrSpotReviewPanel.border          = Margin(0, 0, 0, 0);
		ifrSpotReviewPanel.edge            = Margin(0, 0, 0, 0);

		labeliFrSpot.size                  = Size(400, 9);
		labeliFrSpot.font                  = Font(L"Philips Healthcare Font", 34, false, false, false, false, Font::Antialias::High);
		labeliFrSpot.layout                = Layout::Fill;
		labeliFrSpot.text                  = L"iFR";
		labeliFrSpot.color                 = Palette::Gray070;
		labeliFrSpot.horizontalAlign       = HAlign::Center;
		labeliFrSpot.verticalAlign         = VAlign::Middle;

		labeliFrSpotValue.position         = Point(0, 17);
		labeliFrSpotValue.size             = Size(400, 9);
		labeliFrSpotValue.font             = Font(L"Philips Healthcare Font", 36, false, false, false, false, Font::Antialias::High);
		labeliFrSpotValue.layout           = Layout::Fill;
		labeliFrSpotValue.text             = L"---";
		labeliFrSpotValue.color            = Palette::Gray070;
		labeliFrSpotValue.horizontalAlign  = HAlign::Center;
		labeliFrSpotValue.verticalAlign    = VAlign::Middle;

		graphLayoutPanel.name              = L"graphLayoutPanel";
		graphLayoutPanel.position          = Point(88, 168);
		graphLayoutPanel.size              = Size(760, 600);
		graphLayoutPanel.layoutOuterMargin = Margin(2, 8, 0, 0);
		graphLayoutPanel.layoutSpacing     = 0;

		graphPanel.name                    = L"graphPanel";
		graphPanel.position                = Point(2, 8);
		graphPanel.size                    = Size(758, 592);
		graphPanel.layout                  = Layout::Fill;
		graphPanel.border                  = Margin(0, 0, 0, 0);
		graphPanel.edge                    = Margin(0, 0, 0, 0);

		layoutUpdateEnd();
	}

public:

	Panel                          panelPopup;
	Panel                          popupPanelHeader;
	Label                          popupPanelHeaderText;
	Panel                          topLayOutPannel;
	Control                        panelValues;
	Panel                          firstRowPanel;
	Control                        panelPaNames;
	Label                          labelPa;
	Label                          labelPaValue;
	Panel                          panelPaPdNames;
	Label                          labelPdPa;
	Label                          labelPdPaValue;
	Panel                          secontRowPanel;
	Control                        panelPdNames;
	Label                          labelPd;
	Label                          labelPdValue;
	Panel                          paneliFrFfrNames;
	Label                          labeliFRfFR;
	Label                          labeliFRfFRValue;
	Panel                          progressPanel;
	PciProgressBar                 progress;
	SmartSuiteFullHDIfrReviewPanel ifrReviewPanel;
	Panel                          ifrSpotReviewPanel;
	Label                          labeliFrSpot;
	Label                          labeliFrSpotValue;
	Spacer                         graphLayoutPanel;
	Panel                          graphPanel;

private:

	SmartSuiteFullHDCoregUi(const SmartSuiteFullHDCoregUi&);
	SmartSuiteFullHDCoregUi& operator=(const SmartSuiteFullHDCoregUi&);
};

}}