/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>

namespace Pci { namespace Core
{
using namespace Sense;
using namespace Sense::ExperienceIdentity;

class SmartSuiteFlexvisionIfrReviewPanel : public Panel
{
public:

	SmartSuiteFlexvisionIfrReviewPanel(Control &parent)
	:
		Panel(parent)
		#pragma region Sense Composer (do not modify)
	,	fmTypeLabel      (*this)
	,	distalFmValueLabel(*this)
	,	ifrTrendLabel    (*this)
	,	fmTrendValue     (*this)
		#pragma endregion
	{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		name                             = L"fmReviewPanel";
		size                             = Size(310, 206);
		border                           = Margin(0, 0, 0, 0);
		edge                             = Margin(0, 0, 0, 0);
		colorEdge                        = Color::fromRgb(0, 0, 0);
		fmTypeLabel.name                 = L"fmTypeLabel";
		fmTypeLabel.position             = Point(0, 24);
		fmTypeLabel.size                 = Size(310, 56);
		fmTypeLabel.font                 = Font(L"Philips Healthcare Font", 42, true, false, false, false, Font::Antialias::Low);
		fmTypeLabel.text                 = L"FFR";
		fmTypeLabel.color                = Palette::Gray070;
		fmTypeLabel.horizontalAlign      = HAlign::Center;
		distalFmValueLabel.name          = L"distalFmValueLabel";
		distalFmValueLabel.position      = Point(0, 80);
		distalFmValueLabel.size          = Size(310, 56);
		distalFmValueLabel.font          = Font(L"Philips Healthcare Font", 42, true, false, false, false, Font::Antialias::Low);
		distalFmValueLabel.text          = L"---";
		distalFmValueLabel.color         = Palette::Gray070;
		distalFmValueLabel.horizontalAlign = HAlign::Center;
		ifrTrendLabel.name               = L"ifrTrendLabel";
		ifrTrendLabel.position           = Point(16, 160);
		ifrTrendLabel.size               = Size(136, 40);
		ifrTrendLabel.font               = Font(L"Philips Healthcare Font", 28, false, false, false, false, Font::Antialias::High);
		ifrTrendLabel.text               = L"Trend";
		ifrTrendLabel.color              = Palette::Gray070;
		fmTrendValue.name                = L"fmTrendValue";
		fmTrendValue.position            = Point(200, 160);
		fmTrendValue.size                = Size(72, 40);
		fmTrendValue.font                = Font(L"Philips Healthcare Font", 28, false, false, false, false, Font::Antialias::High);
		fmTrendValue.text                = L"---";
		fmTrendValue.color               = Palette::Gray070;
		fmTrendValue.horizontalAlign     = HAlign::Right;
		layoutUpdateEnd();
		#pragma endregion
	}

	#pragma region Sense Composer (do not modify)
	public:    Label             fmTypeLabel;
	public:    Label             distalFmValueLabel;
	public:    Label             ifrTrendLabel;
	public:    Label             fmTrendValue;
	#pragma endregion

private:

	SmartSuiteFlexvisionIfrReviewPanel(const SmartSuiteFlexvisionIfrReviewPanel&);
	SmartSuiteFlexvisionIfrReviewPanel& operator=(const SmartSuiteFlexvisionIfrReviewPanel&);
};

}}
