// ********************* WARNING *****************************
// * This file was automatically generated by Sense Composer *
// *      Modifying this file manually is frowned upon       *
// ***********************************************************
#pragma once

#include <Sense.h>
#include <ExperienceIdentity.h>

namespace Pci { namespace Core { namespace UI
{

using namespace Sense;
using namespace Sense::ExperienceIdentity;

class StateControlUtility : public Control
{
public:

	StateControlUtility(Control &parent)
	:
		Control              (parent),
		panel                (*this),
		labelCurrent         (panel),
		labelCurrentState    (panel),
		groupSetState        (*this),
		listStates           (groupSetState),
		panel2               (*this),
		labelXRay            (panel2),
		checkXrayConnected   (panel2),
		panel3               (*this),
		labelCoreg           (panel3),
		checkUnreliableCoreg (panel3)
	{
		layoutUpdateBegin();

		size                            = Size(304, 336);
		layoutSpacing                   = 0;

		panel.size                      = Size(304, 32);
		panel.layout                    = Layout::Fixed1d;
		panel.layoutOrientation         = Orientation::Horizontal;

		labelCurrent.size               = Size(80, 29);
		labelCurrent.font               = Font(L"Segoe UI", 20, false, false, false, false, Font::Antialias::High);
		labelCurrent.layout             = Layout::Fixed1d;
		labelCurrent.text               = L"Current:";
		labelCurrent.verticalAlign      = VAlign::Middle;

		labelCurrentState.position      = Point(88, 0);
		labelCurrentState.size          = Size(214, 29);
		labelCurrentState.font          = Font(L"Segoe UI", 20, false, false, false, false, Font::Antialias::High);
		labelCurrentState.layout        = Layout::Fill;
		labelCurrentState.text          = L"Idle";
		labelCurrentState.verticalAlign = VAlign::Middle;

		groupSetState.position          = Point(0, 32);
		groupSetState.size              = Size(304, 256);
		groupSetState.font              = Font(L"Segoe UI", 15, false, false, false, false, Font::Antialias::High);
		groupSetState.layout            = Layout::Fill;
		groupSetState.layoutOuterMargin = Margin(3, 0, 3, 3);
		groupSetState.text              = L"Set state:";

		listStates.position             = Point(3, 0);
		listStates.size                 = Size(296, 222);
		listStates.layout               = Layout::Fill;

		panel2.position                 = Point(0, 288);
		panel2.size                     = Size(304, 24);
		panel2.layout                   = Layout::Fixed1d;
		panel2.layoutOrientation        = Orientation::Horizontal;

		labelXRay.name                  = L"";
		labelXRay.size                  = Size(48, 21);
		labelXRay.layout                = Layout::Fixed1d;
		labelXRay.text                  = L"X-Ray:";
		labelXRay.verticalAlign         = VAlign::Middle;

		checkXrayConnected.position     = Point(56, 0);
		checkXrayConnected.size         = Size(246, 21);
		checkXrayConnected.layout       = Layout::Fill;
		checkXrayConnected.text         = L"Connected";

		panel3.position                 = Point(0, 312);
		panel3.size                     = Size(304, 24);
		panel3.layout                   = Layout::Fixed1d;
		panel3.layoutOrientation        = Orientation::Horizontal;

		labelCoreg.size                 = Size(48, 21);
		labelCoreg.layout               = Layout::Fixed1d;
		labelCoreg.text                 = L"Coreg";
		labelCoreg.verticalAlign        = VAlign::Middle;

		checkUnreliableCoreg.position   = Point(56, 0);
		checkUnreliableCoreg.size       = Size(246, 21);
		checkUnreliableCoreg.layout     = Layout::Fill;
		checkUnreliableCoreg.text       = L"Unreliable connection";

		layoutUpdateEnd();
	}

public:

	Panel    panel;
	Label    labelCurrent;
	Label    labelCurrentState;
	GroupBox groupSetState;
	ListBox  listStates;
	Panel    panel2;
	Label    labelXRay;
	CheckBox checkXrayConnected;
	Panel    panel3;
	Label    labelCoreg;
	CheckBox checkUnreliableCoreg;

private:

	StateControlUtility(const StateControlUtility&);
	StateControlUtility& operator=(const StateControlUtility&);
};

}}}